src/Entity/Registration.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RegistrationRepository")
 */
class Registration
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $payment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Lesson", inversedBy="registrations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $registration;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="registrations")
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPayment(): ?string
    {
        return $this->payment;
    }

    public function setPayment(?string $payment): self
    {
        $this->payment = $payment;

        return $this;
    }

    public function getRegistration(): ?Lesson
    {
        return $this->registration;
    }

    public function setRegistration(?Lesson $registration): self
    {
        $this->registration = $registration;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/admin.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} Training Centrum Den Haag{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
              integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('/css/font-awesome.css') }}">
        <link rel="stylesheet" href="{{ asset('index.css') }}">
    {% endblock %}
    {% block javascripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>
{% block body %}

    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a href="#" class="navbar-brand">
            <img src="{{ asset('image/logo.jpg') }}" alt="logo" style="width:50px;">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('viewInstructor') }}">Instructeur</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('leden')  }}">Leden</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('training_index')  }}">Trainingen</a>
                </li>

            </ul>
            <div class="navbar-nav ml-auto">
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <button type="button" class="btn btn-light" style="margin-right: 5px;"> <a href="{{ path('app_logout') }}">Uitloggen</a></button>
                {% else %}
                    <button type="button" class="btn btn-light" style="margin-right: 5px;"> <a href="{{ path ('login') }}">Inloggen</a></button>
                {% endif %}

                <button type="button" class="btn btn-light">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        Ingelogd : {{ app.user.firstname }} {{ app.user.lastname }}
                    {% else %}
                        Niet ingelogd
                    {% endif %}
                </button>
            </div>
        </div>
    </nav>
{% endblock %}


</body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} Training Centrum Den Haag{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
              integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('/css/font-awesome.css') }}">
        <link rel="stylesheet" href="{{ asset('index.css') }}">
    {% endblock %}
    {% block javascripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
<body>

{% block nav %}
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a href="#" class="navbar-brand">
            <img src="{{ asset('image/logo.jpg') }}" alt="logo" style="width:50px;">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}">Home</a>
                </li>
                {% if is_granted('ROLE_USER') %}
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('registration')  }}">Lid worden</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('gedrag')  }}">Gedragregels</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('contact')  }}">Locatie & Contact</a>
                </li>

                {% if is_granted('ROLE_USER') %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('agenda')  }}">Les Aanbod</a>
                    </li>
                {% endif %}

            </ul>
            <div class="navbar-nav ml-auto">

                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <button type="button" class="btn btn-light" style="margin-right: 5px;"> <a href="{{ path('app_logout') }}">Uitloggen</a></button>
                {% else %}
                    <button type="button" class="btn btn-light" style="margin-right: 5px;"> <a href="{{ path ('login') }}">Inloggen</a></button>
                {% endif %}

                <button type="button" class="btn btn-light">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        Ingelogd : {{ app.user.firstname }} {{ app.user.lastname }}
                    {% else %}
                        Niet ingelogd
                    {% endif %}
                </button>
                {% if is_granted('ROLE_USER') %}
                    <li class="nav navbar-nav navbar-right">
                        <a class="nav-nav-item nav-link" href="{{ path('profieledit')  }}">Profiel</a>
                    </li>
                {% endif %}
                {% if is_granted('ROLE_ADMIN') %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('training_index')  }}">Administrator</a>
                    </li>
                {% endif %}
                {% if is_granted('ROLE_INSTRUCTOR') %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('planlessen')  }}">Instructeur</a>
                    </li>
                {% endif %}

            </div>
        </div>
    </nav>
    {% endblock %}

{% block body %}

{% endblock %}
    </body>
</div>
</html>

templates/bezoeker.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} Training Centrum Den Haag{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
              integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('/css/font-awesome.css') }}">
        <link rel="stylesheet" href="{{ asset('index.css') }}">
    {% endblock %}
    {% block javascripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
{% block body %}
{% block nav %}

    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a href="#" class="navbar-brand">
            <img src="{{ asset('image/logo.jpg') }}" alt="logo" style="width:50px;">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('agenda') }}">Inschrijven op les</a>
                </li>
                {% if is_granted('ROLE_USER') %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('overzichtInschrijvingen') }}">Overzicht inschrijvingen</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('profieledit') }}">Gegevens Wijzigen</a>
            </ul>
            <div class="navbar-nav ml-auto">
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <button type="button" class="btn btn-light" style="margin-right: 5px;"> <a href="{{ path('app_logout') }}">Uitloggen</a></button>
                {% else %}
                    <button type="button" class="btn btn-light" style="margin-right: 5px;"> <a href="{{ path ('login') }}">Inloggen</a></button>
                {% endif %}

                <button type="button" class="btn btn-light">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        Ingelogd : {{ app.user.firstname }} {{ app.user.lastname }}
                    {% else %}
                        Niet ingelogd
                    {% endif %}
                </button>
            </div>
        </div>
    </nav>

{% endblock %}


{% endblock %}

</div>
</html>

templates/instructeur.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %} Training Centrum Den Haag{% endblock %}</title>
    {% block stylesheets %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
              integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ asset('/css/font-awesome.css') }}">
        <link rel="stylesheet" href="{{ asset('index.css') }}">
    {% endblock %}
    {% block javascripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    {% endblock %}
</head>
{% block body %}
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a href="#" class="navbar-brand">
            <img src="{{ asset('image/logo.jpg') }}" alt="logo" style="width:50px;">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('homepage') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('planlessen') }}">Lessen Plannen</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('lesBeheer')  }}">Overzicht inschrijvingen</a>
                </li>
            </ul>
            <div class="navbar-nav ml-auto">
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <button type="button" class="btn btn-light" style="margin-right: 5px;"> <a href="{{ path('app_logout') }}">Uitloggen</a></button>
                {% else %}
                    <button type="button" class="btn btn-light" style="margin-right: 5px;"> <a href="{{ path ('login') }}">Inloggen</a></button>
                {% endif %}

                <button type="button" class="btn btn-light">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                        Ingelogd : {{ app.user.firstname }} {{ app.user.lastname }}
                    {% else %}
                        Niet ingelogd
                    {% endif %}
                </button>
            </div>
        </div>
    </nav>
    {% endblock %}
</div>
</html>